
spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/testTaskNTT
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true


